language: node_js

sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_504b0936ac9e_key -iv $encrypted_504b0936ac9e_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
# 改变文件权限
- chmod 600 ~/.ssh/id_rsa
# 配置 ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
# 配置 git 替换为自己的信息
- git config --global user.name 'reylcc'
- git config --global user.email reylcc@gmail.com

install:
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g
- hexo d
