# Blog info
blog_name: reylcc's Blog
slogan: Just try to be the one you want to be. Give up the rest for the time being.
url: http://absurd.cc

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: reylcc,iOS,ruby,rails,Ruby on Rails

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  # - name: Project
  #   url: /project/
  #   target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/reylcc
    target_blank: true
  - name: Twitter
    url: https://twitter.com/reylcc
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  # - name: 友链
  #   url: /link/
  #   target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: false # true|fase
  text: Just try to be the one you want to be. Give up the rest for the time being.

link_slogan:
  isShow: false # true|fase
  text: Just try to be the one you want to be. Give up the rest for the time being.

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style
personal_style: /css/personal-style.css

home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics:

# Comment service
disqus_shortname: reylcc
# duoshuo_shortname: forsigner


# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "reylcc"
    - "iOS / Ruby on Rails"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@reylcc"
    text_value_url: https://github.com/reylcc
  - type: twitter
    icon: icon-twitter
    text_key: Twitter
    text_value: "@reylcc"
    text_value_url: https://twitter.com/reylcc
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "reylcc@gmail.com"
  - type: location
    icon: icon-location
    text_value: XM

link:
  - name: 织网
    info: 身体和灵魂，总有一个在路上
    url: http://zheng-ji.info/
    avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=100
  - name: Dongyado
    info: 生命不止，折腾不息
    url: http://dongyado.com/
    avatar: https://avatars0.githubusercontent.com/u/6274940?v=3&s=100

project:
  - type: personal
    name: fexo
    url: https://github.com/forsigner/fexo
    intro: A minimalist design theme for hexo
  - type: personal
    name: beside
    url: https://github.com/forsigner/beside
    intro: I need you beside me
